### ISSUE TITLE
Haskoin/Store/Web.hs:529:12: error: [GHC-39999] • Could not deduce ‘Default S.Options’ arising from a use of ‘def’

### ISSUE THREAD

**Issue by juhp** [jprupp/haskoin-store#32]
haskoin-store-1.5.16 fails to build with scotty-0.30 (for latest stackage nightly):

```
       Building library for haskoin-store-1.5.16...                                                                                 
       [ 1 of 11] Compiling Haskoin.Store.Common                                                                                    
       [ 2 of 11] Compiling Haskoin.Store.Database.Types                                                                            
       [ 3 of 11] Compiling Haskoin.Store.Database.Reader                                                                           
       [ 4 of 11] Compiling Haskoin.Store.Cache
       [ 5 of 11] Compiling Haskoin.Store.Database.Writer                                                                           
       [ 6 of 11] Compiling Haskoin.Store.Logic                                                                                     
       [ 7 of 11] Compiling Haskoin.Store.BlockStore              
       [ 8 of 11] Compiling Haskoin.Store.Manager                                                                                   
       [ 9 of 11] Compiling Haskoin.Store.Web                                                                                       
       /home/curators/work/unpack-dir/unpacked/haskoin-store-1.5.16-f687739c4abdd725155c3270891420d82be50a5cf3176707db513838ec108917
/src/Haskoin/Store/Web.hs:529:12: error: [GHC-39999]              
           • Could not deduce ‘Default S.Options’ arising from a use of ‘def’                                                       
             from the context: (MonadUnliftIO m, MonadLoggerIO m)                                                                   
               bound by the type signature for:                                                                                     
                          runWeb :: forall (m :: * -> *).         
                                    (MonadUnliftIO m, MonadLoggerIO m) =>                                                           
                                    WebConfig -> m ()
               at src/Haskoin/Store/Web.hs:501:1-65
           • In the expression: def                                                                                                 
             In a record update at field ‘S.settings’,            
             with type constructor ‘S.Options’                    
             and data constructor ‘S.Options’.                                                                                      
             In the expression: def {S.settings = settings defaultSettings}                                                         
           |                                                                                                                        
       529 |     opts = def {S.settings = settings defaultSettings}                                                                 
           |            ^^^
```
